/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health check
     * @description Basic liveness check. Returns 200 when the API is up.
     */
    get: operations['getHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/keys': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Request an API key
     * @description Start API-key signup for an email address. Emails a 6-digit verification code; no API key is issued until the code is confirmed via POST /v1/keys/confirm. Rate-limited per IP.
     */
    post: operations['registerKey']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/keys/confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Confirm the code and receive the API key
     * @description Exchange the 6-digit code from the verification email for the API key. Identify the pending signup with either `email` or the `rid` from the email link. The API key is returned exactly once — it is stored hashed and cannot be recovered. Five wrong attempts discard the pending signup.
     */
    post: operations['confirmKey']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/qr': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Render a QR code (simple)
     * @description Render a QR code from a content string and an optional preset. The content is encoded exactly as given. Returns the image directly. For full designs (palettes, gradients, logos), use POST /v1/qr. Requires an API key: Authorization: Bearer qk_live_….
     */
    get: operations['renderQrCode']
    put?: never
    /**
     * Render a QR code (full design)
     * @description Render a QR code from a content string and a full QrDesignConfig. Returns the image bytes (SVG or PNG per `format`). Requires an API key: Authorization: Bearer qk_live_…. Despite using POST (to carry the design body), this is a safe, idempotent operation with no side effects — responses may be freely retried and cached.
     */
    post: operations['renderQrCodeWithDesign']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: never
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            status: string
            timestamp: string
          }
        }
      }
    }
  }
  registerKey: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          /**
           * Format: email
           * @description The address the API key is issued to. The 6-digit verification code is sent here. Confirming again later rotates the key in place, so this address stays the account.
           */
          email: string
          /**
           * @description Language for the verification email.
           * @default en
           * @enum {string}
           */
          lang?: 'en' | 'de'
        }
      }
    }
    responses: {
      /** @description Default Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            message: string
          }
        }
      }
      /** @description Invalid email address, malformed code, or neither identifier supplied. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description The code is wrong, expired, or the pending signup was burned by too many attempts. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Rate limit exceeded. Carries `retry-after` (seconds to wait) plus `x-ratelimit-limit`, `x-ratelimit-remaining` and `x-ratelimit-reset` (seconds until the window resets). Successful responses carry the three `x-ratelimit-*` headers too, so a client can pace itself without ever provoking a 429. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
    }
  }
  confirmKey: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          /** @description The 6-digit code from the verification email. Five wrong attempts void the pending signup and you have to start over. */
          code: string
          /**
           * Format: email
           * @description The address the code was sent to. Provide either this or `rid`.
           */
          email?: string
          /** @description Reference from the link in the verification email (`?r=…`), so someone arriving that way need not retype their address. Provide either this or `email`. It selects the pending signup but authorizes nothing on its own — the code does that. */
          rid?: string
        }
      }
    }
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            apiKey: string
            replaced: boolean
          }
        }
      }
      /** @description Invalid email address, malformed code, or neither identifier supplied. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description The code is wrong, expired, or the pending signup was burned by too many attempts. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Rate limit exceeded. Carries `retry-after` (seconds to wait) plus `x-ratelimit-limit`, `x-ratelimit-remaining` and `x-ratelimit-reset` (seconds until the window resets). Successful responses carry the three `x-ratelimit-*` headers too, so a client can pace itself without ever provoking a 429. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
    }
  }
  renderQrCode: {
    parameters: {
      query: {
        /** @description The value encoded into the QR code, verbatim — usually a URL, but any string works, including payload formats such as `WIFI:T:WPA;S:Cafe;P:secret;;`, `mailto:…` or a vCard. The API does not assemble those formats for you. */
        content: string
        /** @description Output format. This alone selects the response media type — the `Accept` header is not consulted. */
        format?: 'svg' | 'png'
        /** @description A built-in design preset, which brings the module and finder styles along with its own colors. `bg` and `margin` always override it. `dark` fully repaints the pattern only for presets that draw their modules in a single color. Most carry a multi-color palette, which takes precedence, and then `dark` changes part of the design or nothing at all — recolor one of those with `modulePalette` on POST /v1/qr instead. */
        preset?:
          | 'classic'
          | 'modern'
          | 'elegant'
          | 'midnight'
          | 'ocean'
          | 'sunset'
          | 'forest'
          | 'brushstroke'
          | 'calligraphy'
          | 'mosaic'
          | 'doodle'
          | 'paintSplash'
          | 'critters'
          | 'pacman'
          | 'halloween'
          | 'brixx'
          | 'tetris'
          | 'bubbles'
          | 'botanical'
          | 'autumn'
          | 'grass'
          | 'bacteria'
          | 'organic'
          | 'circuit'
          | 'connected'
          | 'rainyDay'
          | 'blocky'
          | 'christmas'
          | 'valentines'
          | 'icy'
          | 'summer'
          | 'newYear'
          | 'fiesta'
          | 'carnival'
          | 'purple-chain'
          | 'explosion'
          | 'nickelodeon'
          | 'glitched'
          | 'cyberpunk'
          | 'handmade'
          | 'retroWave'
          | 'neonDrip'
          | 'slimer'
          | 'arcade'
          | 'tropicalPunch'
          | 'discoFloor'
          | 'vinylGroove'
          | 'zigzag'
          | 'midCentury'
          | 'retroTriangle'
          | 'retroWave70s'
          | 'synthwave'
          | 'hypnotic'
          | 'pinwheel'
          | 'galaxy'
          | 'patchwork'
          | 'stitches'
          | 'puzzle'
          | 'instagram'
          | 'whatsapp'
          | 'youtube'
          | 'tiktok'
          | 'linkedin'
          | 'facebook'
          | 'darkBush'
          | 'minecraft'
          | 'architecture'
          | 'candyBlocks'
          | 'escher'
          | 'dither'
          | 'ditherRainbow'
          | 'deepBlue'
          | 'oldFilm'
          | 'el-nino'
          | 'petals'
          | 'washi-tape'
          | 'comic-fries'
          | 'vernissage'
          | 'comic-bricks'
          | 'windswept'
          | 'woodwork'
          | 'blotchy'
          | 'morseCode'
          | 'ripple'
          | 'florist'
          | 'boa'
        /** @description Image width and height in pixels. Defaults to 300 for SVG and 1024 for PNG. */
        size?: number
        /** @description Quiet zone around the QR code, in modules. One module is the minimum, so 0 and 1 both render a single-module zone. */
        margin?: number
        /** @description Module (foreground) color, as `#rgb`, `#rrggbb` or `#rrggbbaa`. Defaults to black unless a preset sets it — see `preset` for when this takes effect. */
        dark?: string
        /** @description Background color, as `#rgb`, `#rrggbb` or `#rrggbbaa`. Defaults to white unless a preset sets it. */
        bg?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The rendered QR code image — SVG or PNG per the requested `format`. The response `Content-Type` names the format actually returned and is authoritative. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'image/svg+xml': string
          'image/png': string
        }
      }
      /** @description Content or design failed validation, or the format is unsupported. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description API key missing, malformed, unknown, or revoked. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Custom logo or requested PNG size over the cap. */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Valid input that cannot be encoded — usually content too long for a QR code. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Rate limit exceeded. Carries `retry-after` (seconds to wait) plus `x-ratelimit-limit`, `x-ratelimit-remaining` and `x-ratelimit-reset` (seconds until the window resets). Successful responses carry the three `x-ratelimit-*` headers too, so a client can pace itself without ever provoking a 429. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Render failure. Logged on our side. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
    }
  }
  renderQrCodeWithDesign: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          /** @description The value encoded into the QR code, verbatim — usually a URL, but any string works, including payload formats such as `WIFI:T:WPA;S:Cafe;P:secret;;`, `mailto:…` or a vCard. The API does not assemble those formats for you. */
          content: string
          /**
           * @description The full design — module and finder styles, colors, logo and halo. The QR Designer on qrocodile.io produces exactly this object: design the QR code there, then use its “Copy JSON” button and paste the result here. One exception: an animated design also carries an `animation` field, which this endpoint rejects because it renders a single image — remove that field to render a still.
           * @default {}
           */
          design?: {
            /**
             * @description A built-in preset loaded as the starting point. Fields set alongside it override the preset’s own values, so a preset plus `moduleColor` is a recolored preset.
             * @enum {string}
             */
            preset?:
              | 'classic'
              | 'modern'
              | 'elegant'
              | 'midnight'
              | 'ocean'
              | 'sunset'
              | 'forest'
              | 'brushstroke'
              | 'calligraphy'
              | 'mosaic'
              | 'doodle'
              | 'paintSplash'
              | 'critters'
              | 'pacman'
              | 'halloween'
              | 'brixx'
              | 'tetris'
              | 'bubbles'
              | 'botanical'
              | 'autumn'
              | 'grass'
              | 'bacteria'
              | 'organic'
              | 'circuit'
              | 'connected'
              | 'rainyDay'
              | 'blocky'
              | 'christmas'
              | 'valentines'
              | 'icy'
              | 'summer'
              | 'newYear'
              | 'fiesta'
              | 'carnival'
              | 'purple-chain'
              | 'explosion'
              | 'nickelodeon'
              | 'glitched'
              | 'cyberpunk'
              | 'handmade'
              | 'retroWave'
              | 'neonDrip'
              | 'slimer'
              | 'arcade'
              | 'tropicalPunch'
              | 'discoFloor'
              | 'vinylGroove'
              | 'zigzag'
              | 'midCentury'
              | 'retroTriangle'
              | 'retroWave70s'
              | 'synthwave'
              | 'hypnotic'
              | 'pinwheel'
              | 'galaxy'
              | 'patchwork'
              | 'stitches'
              | 'puzzle'
              | 'instagram'
              | 'whatsapp'
              | 'youtube'
              | 'tiktok'
              | 'linkedin'
              | 'facebook'
              | 'darkBush'
              | 'minecraft'
              | 'architecture'
              | 'candyBlocks'
              | 'escher'
              | 'dither'
              | 'ditherRainbow'
              | 'deepBlue'
              | 'oldFilm'
              | 'el-nino'
              | 'petals'
              | 'washi-tape'
              | 'comic-fries'
              | 'vernissage'
              | 'comic-bricks'
              | 'windswept'
              | 'woodwork'
              | 'blotchy'
              | 'morseCode'
              | 'ripple'
              | 'florist'
              | 'boa'
            /**
             * @description Shape the modules (the pattern) are drawn with. The enum lists every style this build can render.
             * @enum {string}
             */
            moduleStyleId?:
              | 'classic'
              | 'photo-overlay'
              | 'bacteria'
              | 'blocky'
              | 'botanical'
              | 'bubbles'
              | 'calligraphy'
              | 'vortex'
              | 'chevron'
              | 'circuits'
              | 'connected'
              | 'diamond'
              | 'doodle'
              | 'double-bubble'
              | 'drip'
              | 'explosion'
              | 'film'
              | 'ink-pen'
              | 'washi-tape'
              | 'comic-fries'
              | 'woodwork'
              | 'blotchy'
              | 'glitch'
              | 'grass'
              | 'halfmoon'
              | 'leaves'
              | 'characters'
              | 'brixx'
              | 'wavy'
              | 'dither'
              | 'megaShapes'
              | 'mosaic'
              | 'neighborAware'
              | 'organic'
              | 'pacman'
              | 'patchwork'
              | 'pizza'
              | 'puzzle'
              | 'raindrop'
              | 'artist'
              | 'paint-strokes'
              | 'retro'
              | 'rotated'
              | 'roundedDots'
              | 'roundedSquares'
              | 'tetris'
              | 'sketch'
              | '3d'
              | 'triangle'
              | 'spiky'
              | 'overlay'
              | 'petals'
              | 'variedDots'
              | 'ripple'
              | 'isometric'
            /** @description Tuning parameters for the chosen style. Which keys are accepted depends on the style — the QR Designer exposes them as that style’s own sliders. */
            moduleStyleParams?: {
              [key: string]: number | string
            }
            /**
             * @description Shape the three corner finders are drawn with.
             * @enum {string}
             */
            finderStyleId?:
              | 'classic'
              | 'modern'
              | 'carved'
              | 'scribble'
              | 'drip'
              | 'eroded'
              | 'comic'
              | 'blotchy'
              | 'shifted'
              | 'meadow'
              | 'leaf'
              | 'morphing'
              | 'pill'
              | 'sketchy'
              | 'stamp'
              | 'sticker'
              | 'segmented'
              | 'dotted'
            /** @description Tuning parameters for the chosen style. Which keys are accepted depends on the style — the QR Designer exposes them as that style’s own sliders. */
            finderStyleParams?: {
              [key: string]: number | string
            }
            /** @description Let the module style draw the corner finders itself. Only effective for styles that can render finders, and the only way to express relief and 3D designs whose corners must stay depth-sorted with the pattern. Supersedes `finderStyleId`. */
            finderUseModuleStyle?: boolean
            /** @description Corners take their per-cell color from the pattern instead of `finderFrameColor` and `finderEyeColor`. */
            finderColorInherit?: boolean
            /** @description Color of the modules — a solid hex color or a gradient. */
            moduleColor?:
              | string
              | {
                  /**
                   * @description Gradient geometry.
                   * @enum {string}
                   */
                  type: 'linear' | 'radial'
                  /**
                   * @description Angle of a linear gradient, in degrees. Ignored by a radial gradient.
                   * @default 0
                   */
                  angle?: number
                  /** @description Two to sixteen color stops, spread evenly unless placed. A stop is either a color string or `{ color, offset }` with `offset` between 0 and 1. */
                  stops: (
                    | string
                    | {
                        /** @description The stop’s color. */
                        color: string
                        /** @description Where the stop sits along the gradient, 0 = start, 1 = end. */
                        offset: number
                      }
                  )[]
                }
            /** @description Draw the modules from several colors at once, arranged by `paletteMode`. Use this instead of `moduleColor` for multi-color patterns. */
            modulePalette?: string[]
            /**
             * @description How the palette colors are distributed across the modules.
             * @default scatter
             * @enum {string}
             */
            paletteMode?:
              | 'scatter'
              | 'horizontal'
              | 'vertical'
              | 'diagonal'
              | 'radial'
              | 'checkerboard'
              | 'spiral'
              | 'wave'
              | 'noise'
              | 'rings'
              | 'mandala'
              | 'lava'
              | 'group'
            /**
             * @description Scale of the pattern that `paletteMode` lays over the modules.
             * @default 1
             */
            paletteScale?: number
            /**
             * @description Jitter of the color-sample position, in modules, which breaks hard palette bands into a grain, off at 0.
             * @default 0
             */
            paletteDither?: number
            /** @description Color of the outer frame of each corner finder. */
            finderFrameColor?:
              | string
              | {
                  /**
                   * @description Gradient geometry.
                   * @enum {string}
                   */
                  type: 'linear' | 'radial'
                  /**
                   * @description Angle of a linear gradient, in degrees. Ignored by a radial gradient.
                   * @default 0
                   */
                  angle?: number
                  /** @description Two to sixteen color stops, spread evenly unless placed. A stop is either a color string or `{ color, offset }` with `offset` between 0 and 1. */
                  stops: (
                    | string
                    | {
                        /** @description The stop’s color. */
                        color: string
                        /** @description Where the stop sits along the gradient, 0 = start, 1 = end. */
                        offset: number
                      }
                  )[]
                }
            /** @description Color of the inner eye of each corner finder. */
            finderEyeColor?:
              | string
              | {
                  /**
                   * @description Gradient geometry.
                   * @enum {string}
                   */
                  type: 'linear' | 'radial'
                  /**
                   * @description Angle of a linear gradient, in degrees. Ignored by a radial gradient.
                   * @default 0
                   */
                  angle?: number
                  /** @description Two to sixteen color stops, spread evenly unless placed. A stop is either a color string or `{ color, offset }` with `offset` between 0 and 1. */
                  stops: (
                    | string
                    | {
                        /** @description The stop’s color. */
                        color: string
                        /** @description Where the stop sits along the gradient, 0 = start, 1 = end. */
                        offset: number
                      }
                  )[]
                }
            /**
             * @description Background color, or `transparent` to leave it unpainted.
             * @default #ffffff
             */
            background?: string | 'transparent'
            /**
             * @description Quiet zone around the QR code, in modules. One module is the minimum, so 0 and 1 both render a single-module zone.
             * @default 2
             */
            margin?: number
            /** @description A logo placed on the QR code: either a built-in icon by `id`, or your own artwork as base64 in `data`. Not both. */
            logo?:
              | {
                  /**
                   * @description Which built-in icon to place. The enum lists every icon this build ships.
                   * @enum {string}
                   */
                  id:
                    | 'youtube'
                    | 'instagram'
                    | 'facebook'
                    | 'x'
                    | 'linkedin'
                    | 'tiktok'
                    | 'snapchat'
                    | 'pinterest'
                    | 'threads'
                    | 'bluesky'
                    | 'whatsapp'
                    | 'telegram'
                    | 'discord'
                    | 'spotify'
                    | 'apple'
                    | 'twitch'
                    | 'website'
                    | 'email'
                    | 'phone'
                    | 'location'
                    | 'wifi'
                    | 'google'
                    | 'paypal'
                    | 'amazon'
                    | 'googleplay'
                    | 'github'
                    | 'kim'
                  /** @description Color the icon is recolored to. */
                  color: string
                  /**
                   * @description Logo width as a fraction of the QR code’s width, between 0.1 and 1. The height follows from the artwork’s aspect ratio.
                   * @default 0.8
                   */
                  regionWidth?: number
                  /**
                   * @description How the modules behave around the logo. `clear` clears a plain rectangle behind it; `float` clears only where the logo is opaque, so the pattern flows around the silhouette — use it for logos with a transparent background; `fill` clears nothing and draws the modules behind the logo.
                   * @default clear
                   * @enum {string}
                   */
                  mode?: 'clear' | 'float' | 'fill'
                  /**
                   * @description Extra cleared margin around the logo silhouette, in modules, which keeps floating modules off the logo’s edge. Float mode only.
                   * @default 0.75
                   */
                  halo?: number
                  /**
                   * @description Draw modules inside the logo’s enclosed gaps — the counter of an “o”, for instance — instead of leaving them clear. Float mode only.
                   * @default false
                   */
                  fillInterior?: boolean
                  /**
                   * @description Horizontal placement of the logo: 0 pushes it as far left as it goes, 0.5 centers it, 1 as far right. The logo stays fully inside the image at either extreme, so neither end crops it.
                   * @default 0.5
                   */
                  posX?: number
                  /**
                   * @description Vertical placement of the logo: 0 pushes it as far up as it goes, 0.5 centers it, 1 as far down. The logo stays fully inside the image at either extreme, so neither end crops it.
                   * @default 0.5
                   */
                  posY?: number
                }
              | {
                  /** @description Your own logo as a base64-encoded image — PNG, JPEG or SVG — either a bare base64 string or a `data:` URL, which is what the QR Designer’s “Copy JSON” emits. Any mime type declared in that URL is ignored: the real format is detected from the bytes. SVG is sanitized before it is drawn. Nothing is ever fetched over the network — an `https:` URL in this field is not downloaded, it just fails to decode. */
                  data: string
                  /**
                   * @description Logo width as a fraction of the QR code’s width, between 0.1 and 1. The height follows from the artwork’s aspect ratio.
                   * @default 0.8
                   */
                  regionWidth?: number
                  /**
                   * @description How the modules behave around the logo. `clear` clears a plain rectangle behind it; `float` clears only where the logo is opaque, so the pattern flows around the silhouette — use it for logos with a transparent background; `fill` clears nothing and draws the modules behind the logo.
                   * @default clear
                   * @enum {string}
                   */
                  mode?: 'clear' | 'float' | 'fill'
                  /**
                   * @description Extra cleared margin around the logo silhouette, in modules, which keeps floating modules off the logo’s edge. Float mode only.
                   * @default 0.75
                   */
                  halo?: number
                  /**
                   * @description Draw modules inside the logo’s enclosed gaps — the counter of an “o”, for instance — instead of leaving them clear. Float mode only.
                   * @default false
                   */
                  fillInterior?: boolean
                  /**
                   * @description Horizontal placement of the logo: 0 pushes it as far left as it goes, 0.5 centers it, 1 as far right. The logo stays fully inside the image at either extreme, so neither end crops it.
                   * @default 0.5
                   */
                  posX?: number
                  /**
                   * @description Vertical placement of the logo: 0 pushes it as far up as it goes, 0.5 centers it, 1 as far down. The logo stays fully inside the image at either extreme, so neither end crops it.
                   * @default 0.5
                   */
                  posY?: number
                }
            /** @description Decoration scattered around the QR code, drawn with the design’s own module style. */
            halo?: {
              /** @description Draw the halo. Sending a `halo` object at all switches it on, so this need only be set to turn one off: `false` keeps the settings below while suppressing the decoration. Omit the whole `halo` object for a design that has none. */
              enabled?: boolean
              /**
               * @description How the halo and the QR code are drawn together. `composite` (layered) leaves the code exactly as it looks without a halo. `unified` (integrated) merges both into one drawing, so 3D styles cast shadows across the halo — at the cost of the code itself looking slightly different.
               * @default composite
               * @enum {string}
               */
              mode?: 'composite' | 'unified'
              /**
               * @description The total light ring the viewer sees between the pattern and the halo, in modules. The code’s own `margin` counts toward it rather than adding to it, so a value at or below `margin` leaves no gap at all — with the default margin of 2, the halo starts right at the code until this reaches 3.
               * @default 1
               */
              quietZone?: number
              /**
               * @description How far the halo reaches beyond the quiet zone, in modules. One module is the minimum, so 0 renders as 1.
               * @default 8
               */
              spread?: number
              /**
               * @description Plain background kept outside the halo, in modules.
               * @default 0
               */
              margin?: number
              /**
               * @description Peak fraction of cells filled, measured nearest the code.
               * @default 0.65
               */
              density?: number
              /**
               * @description How quickly the halo thins out with distance from the code.
               * @default ease
               * @enum {string}
               */
              curve?: 'none' | 'linear' | 'ease' | 'steep'
              /**
               * @description Shape the halo fades along — square, soft square, or round.
               * @default square
               * @enum {string}
               */
              falloff?: 'square' | 'squircle' | 'round'
              /**
               * @description How much the halo modules clump together: 0 scatters them at random, 1 gathers them into smooth clumps.
               * @default 0.3
               */
              cluster?: number
              /**
               * @description Scatter seed. The same seed redraws the same halo, so a render is reproducible; change it for a different arrangement of the same settings.
               * @default 0
               */
              seed?: number
              /** @description Where the halo takes its colors from. */
              color?: {
                /**
                 * @description Where the halo takes its colors from: `inherit` reuses the code’s own pattern colors, `palette` uses the `palette` below.
                 * @default inherit
                 * @enum {string}
                 */
                mode?: 'inherit' | 'palette'
                /** @description Colors the halo is drawn from when `mode` is `palette`. */
                palette?: string[]
                /**
                 * @description How the halo’s palette colors are distributed. Defaults to the code’s own `paletteMode`, or `scatter` when that is unset too.
                 * @enum {string}
                 */
                paletteMode?:
                  | 'scatter'
                  | 'horizontal'
                  | 'vertical'
                  | 'diagonal'
                  | 'radial'
                  | 'checkerboard'
                  | 'spiral'
                  | 'wave'
                  | 'noise'
                  | 'rings'
                  | 'mandala'
                  | 'lava'
                  | 'group'
                /**
                 * @description How far the outermost halo modules fade toward the background. 0 is no fade.
                 * @default 0
                 */
                fade?: number
              }
            }
          }
          /**
           * @description Output format. This alone selects the response media type — the `Accept` header is not consulted.
           * @default svg
           * @enum {string}
           */
          format?: 'svg' | 'png'
          /** @description Image width and height in pixels. Defaults to 300 for SVG and 1024 for PNG. */
          size?: number
          /**
           * @description Nudge low-contrast color combinations apart so the QR code stays scannable. Turn it off to get the colors exactly as given.
           * @default true
           */
          fixContrast?: boolean
        }
      }
    }
    responses: {
      /** @description The rendered QR code image — SVG or PNG per the requested `format`. The response `Content-Type` names the format actually returned and is authoritative. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'image/svg+xml': string
          'image/png': string
        }
      }
      /** @description Content or design failed validation, or the format is unsupported. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description API key missing, malformed, unknown, or revoked. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Custom logo or requested PNG size over the cap. */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Valid input that cannot be encoded — usually content too long for a QR code. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Rate limit exceeded. Carries `retry-after` (seconds to wait) plus `x-ratelimit-limit`, `x-ratelimit-remaining` and `x-ratelimit-reset` (seconds until the window resets). Successful responses carry the three `x-ratelimit-*` headers too, so a client can pace itself without ever provoking a 429. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Render failure. Logged on our side. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
    }
  }
}
