/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health check
     * @description Basic liveness check. Returns 200 when the API is up.
     */
    get: operations['getHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/keys': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Register for an API key
     * @description Start API-key signup for an email address. Sends a one-time confirmation link; no key is issued until the link is opened. Rate-limited per IP.
     */
    post: operations['registerKey']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/keys/confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Confirm email and reveal the API key
     * @description Open the one-time link from the confirmation email to generate the API key. The plaintext key is shown exactly once (HTML page, or JSON with `Accept: application/json`).
     */
    get: operations['confirmKey']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/qr': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Render a QR code (simple)
     * @description Render a QR code from a single content string and an optional preset. Returns the image directly. For structured content (wifi, vcard…) or full designs (palettes, gradients, logos), use POST /v1/qr. Requires Authorization: Bearer <key>.
     */
    get: operations['getQr']
    put?: never
    /**
     * Render a QR code (full design)
     * @description Render a QR code from structured content and a full QrDesignConfig. Returns the image bytes (SVG or PNG per `format`). Requires Authorization: Bearer <key>. Despite using POST (to carry the design body), this is a safe, idempotent operation with no side effects — responses may be freely retried and cached.
     */
    post: operations['createQr']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: never
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            status: string
            timestamp: string
          }
        }
      }
    }
  }
  registerKey: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          /** Format: email */
          email: string
        }
      }
    }
    responses: {
      /** @description Default Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            message: string
          }
        }
      }
      /** @description Invalid email address. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Too many registration attempts. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
    }
  }
  confirmKey: {
    parameters: {
      query: {
        token: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Email confirmed — the API key, shown exactly once. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            apiKey: string
          }
          'text/html': string
        }
      }
      /** @description Invalid or expired confirmation link. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
    }
  }
  getQr: {
    parameters: {
      query: {
        content: string
        type?: 'url' | 'text' | 'tel' | 'email' | 'sms'
        format?: 'svg' | 'png'
        preset?:
          | 'classic'
          | 'modern'
          | 'elegant'
          | 'midnight'
          | 'ocean'
          | 'sunset'
          | 'forest'
          | 'brushstroke'
          | 'calligraphy'
          | 'mosaic'
          | 'doodle'
          | 'paintSplash'
          | 'critters'
          | 'pacman'
          | 'halloween'
          | 'brixx'
          | 'tetris'
          | 'bubbles'
          | 'botanical'
          | 'autumn'
          | 'grass'
          | 'bacteria'
          | 'organic'
          | 'circuit'
          | 'connected'
          | 'rainyDay'
          | 'blocky'
          | 'christmas'
          | 'valentines'
          | 'icy'
          | 'summer'
          | 'newYear'
          | 'fiesta'
          | 'carnival'
          | 'purple-chain'
          | 'explosion'
          | 'nickelodeon'
          | 'glitched'
          | 'cyberpunk'
          | 'handmade'
          | 'retroWave'
          | 'neonDrip'
          | 'slimer'
          | 'arcade'
          | 'tropicalPunch'
          | 'discoFloor'
          | 'vinylGroove'
          | 'zigzag'
          | 'midCentury'
          | 'retroTriangle'
          | 'retroWave70s'
          | 'synthwave'
          | 'hypnotic'
          | 'pinwheel'
          | 'galaxy'
          | 'patchwork'
          | 'stitches'
          | 'puzzle'
          | 'instagram'
          | 'whatsapp'
          | 'youtube'
          | 'tiktok'
          | 'linkedin'
          | 'facebook'
          | 'darkBush'
          | 'minecraft'
          | 'deepBlue'
          | 'oldFilm'
          | 'el-nino'
          | 'petals'
          | 'washi-tape'
          | 'comic-fries'
          | 'vernissage'
          | 'comic-bricks'
          | 'windswept'
          | 'woodwork'
          | 'blotchy'
        size?: number
        margin?: number
        dark?: string
        bg?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The rendered QR code image (SVG or PNG per `format`). */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'image/svg+xml': string
          'image/png': string
        }
      }
      /** @description Invalid content or design. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Missing, invalid, or revoked API key. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Content could not be encoded into a QR code. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
    }
  }
  createQr: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          content:
            | string
            | ({
                type: string
              } & {
                [key: string]: string | number | boolean
              })
          /** @default {} */
          design?: {
            /** @enum {string} */
            preset?:
              | 'classic'
              | 'modern'
              | 'elegant'
              | 'midnight'
              | 'ocean'
              | 'sunset'
              | 'forest'
              | 'brushstroke'
              | 'calligraphy'
              | 'mosaic'
              | 'doodle'
              | 'paintSplash'
              | 'critters'
              | 'pacman'
              | 'halloween'
              | 'brixx'
              | 'tetris'
              | 'bubbles'
              | 'botanical'
              | 'autumn'
              | 'grass'
              | 'bacteria'
              | 'organic'
              | 'circuit'
              | 'connected'
              | 'rainyDay'
              | 'blocky'
              | 'christmas'
              | 'valentines'
              | 'icy'
              | 'summer'
              | 'newYear'
              | 'fiesta'
              | 'carnival'
              | 'purple-chain'
              | 'explosion'
              | 'nickelodeon'
              | 'glitched'
              | 'cyberpunk'
              | 'handmade'
              | 'retroWave'
              | 'neonDrip'
              | 'slimer'
              | 'arcade'
              | 'tropicalPunch'
              | 'discoFloor'
              | 'vinylGroove'
              | 'zigzag'
              | 'midCentury'
              | 'retroTriangle'
              | 'retroWave70s'
              | 'synthwave'
              | 'hypnotic'
              | 'pinwheel'
              | 'galaxy'
              | 'patchwork'
              | 'stitches'
              | 'puzzle'
              | 'instagram'
              | 'whatsapp'
              | 'youtube'
              | 'tiktok'
              | 'linkedin'
              | 'facebook'
              | 'darkBush'
              | 'minecraft'
              | 'deepBlue'
              | 'oldFilm'
              | 'el-nino'
              | 'petals'
              | 'washi-tape'
              | 'comic-fries'
              | 'vernissage'
              | 'comic-bricks'
              | 'windswept'
              | 'woodwork'
              | 'blotchy'
            /** @enum {string} */
            moduleStyleId?:
              | 'classic'
              | 'photo-overlay'
              | 'bacteria'
              | 'blocky'
              | 'botanical'
              | 'bubbles'
              | 'calligraphy'
              | 'vortex'
              | 'chevron'
              | 'circuits'
              | 'connected'
              | 'diamond'
              | 'doodle'
              | 'double-bubble'
              | 'drip'
              | 'explosion'
              | 'film'
              | 'ink-pen'
              | 'washi-tape'
              | 'comic-fries'
              | 'woodwork'
              | 'blotchy'
              | 'glitch'
              | 'grass'
              | 'halfmoon'
              | 'leaves'
              | 'characters'
              | 'brixx'
              | 'wavy'
              | 'megaShapes'
              | 'mosaic'
              | 'neighborAware'
              | 'organic'
              | 'pacman'
              | 'patchwork'
              | 'pizza'
              | 'puzzle'
              | 'raindrop'
              | 'artist'
              | 'paint-strokes'
              | 'retro'
              | 'rotated'
              | 'roundedDots'
              | 'roundedSquares'
              | 'tetris'
              | 'sketch'
              | '3d'
              | 'triangle'
              | 'spiky'
              | 'overlay'
              | 'petals'
              | 'variedDots'
            moduleStyleParams?: {
              [key: string]: number | string
            }
            /** @enum {string} */
            finderStyleId?:
              | 'classic'
              | 'modern'
              | 'brixx'
              | 'carved'
              | 'chevron'
              | 'doodle'
              | 'drip'
              | 'eroded'
              | 'comic'
              | 'woodwork'
              | 'blotchy'
              | 'washi-tape'
              | 'glitch'
              | 'grass'
              | 'halfmoon'
              | 'leaf'
              | 'morphing'
              | 'patchwork'
              | 'pill'
              | 'puzzle'
              | '3d'
              | 'sketchy'
              | 'stamp'
              | 'sticker'
            finderStyleParams?: {
              [key: string]: number | string
            }
            moduleColor?:
              | string
              | {
                  /** @enum {string} */
                  type: 'linear' | 'radial'
                  angle?: number
                  stops: (
                    | string
                    | {
                        color: string
                        offset: number
                      }
                  )[]
                }
            modulePalette?: string[]
            /** @enum {string} */
            paletteMode?:
              | 'scatter'
              | 'horizontal'
              | 'vertical'
              | 'diagonal'
              | 'radial'
              | 'checkerboard'
              | 'spiral'
              | 'wave'
              | 'noise'
              | 'rings'
              | 'mandala'
              | 'lava'
              | 'group'
            paletteScale?: number
            finderFrameColor?:
              | string
              | {
                  /** @enum {string} */
                  type: 'linear' | 'radial'
                  angle?: number
                  stops: (
                    | string
                    | {
                        color: string
                        offset: number
                      }
                  )[]
                }
            finderEyeColor?:
              | string
              | {
                  /** @enum {string} */
                  type: 'linear' | 'radial'
                  angle?: number
                  stops: (
                    | string
                    | {
                        color: string
                        offset: number
                      }
                  )[]
                }
            background?: string | 'transparent'
            margin?: number
            logo?:
              | {
                  /** @enum {string} */
                  id:
                    | 'youtube'
                    | 'instagram'
                    | 'facebook'
                    | 'x'
                    | 'linkedin'
                    | 'tiktok'
                    | 'snapchat'
                    | 'pinterest'
                    | 'threads'
                    | 'bluesky'
                    | 'whatsapp'
                    | 'telegram'
                    | 'discord'
                    | 'spotify'
                    | 'apple'
                    | 'twitch'
                    | 'website'
                    | 'email'
                    | 'phone'
                    | 'location'
                    | 'wifi'
                    | 'google'
                    | 'paypal'
                    | 'amazon'
                    | 'googleplay'
                    | 'github'
                  color: string
                  regionWidth?: number
                }
              | {
                  data: string
                  regionWidth?: number
                  showModules?: boolean
                  posX?: number
                  posY?: number
                }
            overdriveMode?: boolean
          }
          /**
           * @default svg
           * @enum {string}
           */
          format?: 'svg' | 'png'
          size?: number
          /** @default true */
          fixContrast?: boolean
        }
      }
    }
    responses: {
      /** @description The rendered QR code image (SVG or PNG per `format`). */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'image/svg+xml': string
          'image/png': string
        }
      }
      /** @description Invalid content or design. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Missing, invalid, or revoked API key. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Content could not be encoded into a QR code. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Rate limit exceeded. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
    }
  }
}
