/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health check
     * @description Basic liveness check. Returns 200 when the API is up.
     */
    get: operations['getHealth']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/keys': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Request an API key
     * @description Start API-key signup for an email address. Emails a 6-digit verification code; no API key is issued until the code is confirmed via POST /v1/keys/confirm. Rate-limited per IP.
     */
    post: operations['registerKey']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/keys/confirm': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Confirm the code and receive the API key
     * @description Exchange the 6-digit code from the verification email for the API key. Identify the pending signup with either `email` or the `rid` from the email link. The API key is returned exactly once — it is stored hashed and cannot be recovered. Five wrong attempts discard the pending signup.
     */
    post: operations['confirmKey']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/qr': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Render a QR code (simple)
     * @description Render a QR code from a content string and an optional preset. The content is encoded exactly as given. Returns the image directly. For full designs (palettes, gradients, logos), use POST /v1/qr. Requires an API key: Authorization: Bearer qk_live_….
     */
    get: operations['renderQrCode']
    put?: never
    /**
     * Render a QR code (full design)
     * @description Render a QR code from a content string and a full QrDesignConfig. Returns the image bytes (SVG or PNG per `format`). Requires an API key: Authorization: Bearer qk_live_…. Despite using POST (to carry the design body), this is a safe, idempotent operation with no side effects — responses may be freely retried and cached.
     */
    post: operations['renderQrCodeWithDesign']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: never
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  getHealth: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            status: string
            timestamp: string
          }
        }
      }
    }
  }
  registerKey: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          /** Format: email */
          email: string
          /**
           * @default en
           * @enum {string}
           */
          lang?: 'en' | 'de'
        }
      }
    }
    responses: {
      /** @description Default Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            message: string
          }
        }
      }
      /** @description Invalid email address, malformed code, or neither identifier supplied. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description The code is wrong, expired, or the pending signup was burned by too many attempts. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Rate limit exceeded. Carries `retry-after` (seconds to wait) plus `x-ratelimit-limit`, `x-ratelimit-remaining` and `x-ratelimit-reset` (seconds until the window resets). Successful responses carry the three `x-ratelimit-*` headers too, so a client can pace itself without ever provoking a 429. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
    }
  }
  confirmKey: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          code: string
          /** Format: email */
          email?: string
          rid?: string
        }
      }
    }
    responses: {
      /** @description Default Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            apiKey: string
            replaced: boolean
          }
        }
      }
      /** @description Invalid email address, malformed code, or neither identifier supplied. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description The code is wrong, expired, or the pending signup was burned by too many attempts. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Rate limit exceeded. Carries `retry-after` (seconds to wait) plus `x-ratelimit-limit`, `x-ratelimit-remaining` and `x-ratelimit-reset` (seconds until the window resets). Successful responses carry the three `x-ratelimit-*` headers too, so a client can pace itself without ever provoking a 429. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
    }
  }
  renderQrCode: {
    parameters: {
      query: {
        content: string
        format?: 'svg' | 'png'
        preset?:
          | 'classic'
          | 'modern'
          | 'elegant'
          | 'midnight'
          | 'ocean'
          | 'sunset'
          | 'forest'
          | 'brushstroke'
          | 'calligraphy'
          | 'mosaic'
          | 'doodle'
          | 'paintSplash'
          | 'critters'
          | 'pacman'
          | 'halloween'
          | 'brixx'
          | 'tetris'
          | 'bubbles'
          | 'botanical'
          | 'autumn'
          | 'grass'
          | 'bacteria'
          | 'organic'
          | 'circuit'
          | 'connected'
          | 'rainyDay'
          | 'blocky'
          | 'christmas'
          | 'valentines'
          | 'icy'
          | 'summer'
          | 'newYear'
          | 'fiesta'
          | 'carnival'
          | 'purple-chain'
          | 'explosion'
          | 'nickelodeon'
          | 'glitched'
          | 'cyberpunk'
          | 'handmade'
          | 'retroWave'
          | 'neonDrip'
          | 'slimer'
          | 'arcade'
          | 'tropicalPunch'
          | 'discoFloor'
          | 'vinylGroove'
          | 'zigzag'
          | 'midCentury'
          | 'retroTriangle'
          | 'retroWave70s'
          | 'synthwave'
          | 'hypnotic'
          | 'pinwheel'
          | 'galaxy'
          | 'patchwork'
          | 'stitches'
          | 'puzzle'
          | 'instagram'
          | 'whatsapp'
          | 'youtube'
          | 'tiktok'
          | 'linkedin'
          | 'facebook'
          | 'darkBush'
          | 'minecraft'
          | 'architecture'
          | 'candyBlocks'
          | 'escher'
          | 'dither'
          | 'ditherRainbow'
          | 'deepBlue'
          | 'oldFilm'
          | 'el-nino'
          | 'petals'
          | 'washi-tape'
          | 'comic-fries'
          | 'vernissage'
          | 'comic-bricks'
          | 'windswept'
          | 'woodwork'
          | 'blotchy'
          | 'morseCode'
          | 'ripple'
          | 'florist'
          | 'boa'
        size?: number
        margin?: number
        dark?: string
        bg?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description The rendered QR code image — SVG or PNG per the requested `format`. The response `Content-Type` names the format actually returned and is authoritative. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'image/svg+xml': string
          'image/png': string
        }
      }
      /** @description Content or design failed validation, or the format is unsupported. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description API key missing, malformed, unknown, or revoked. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Custom logo or requested PNG size over the cap. */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Valid input that cannot be encoded — usually content too long for a QR code. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Rate limit exceeded. Carries `retry-after` (seconds to wait) plus `x-ratelimit-limit`, `x-ratelimit-remaining` and `x-ratelimit-reset` (seconds until the window resets). Successful responses carry the three `x-ratelimit-*` headers too, so a client can pace itself without ever provoking a 429. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Render failure. Logged on our side. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
    }
  }
  renderQrCodeWithDesign: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          content: string
          /** @default {} */
          design?: {
            /** @enum {string} */
            preset?:
              | 'classic'
              | 'modern'
              | 'elegant'
              | 'midnight'
              | 'ocean'
              | 'sunset'
              | 'forest'
              | 'brushstroke'
              | 'calligraphy'
              | 'mosaic'
              | 'doodle'
              | 'paintSplash'
              | 'critters'
              | 'pacman'
              | 'halloween'
              | 'brixx'
              | 'tetris'
              | 'bubbles'
              | 'botanical'
              | 'autumn'
              | 'grass'
              | 'bacteria'
              | 'organic'
              | 'circuit'
              | 'connected'
              | 'rainyDay'
              | 'blocky'
              | 'christmas'
              | 'valentines'
              | 'icy'
              | 'summer'
              | 'newYear'
              | 'fiesta'
              | 'carnival'
              | 'purple-chain'
              | 'explosion'
              | 'nickelodeon'
              | 'glitched'
              | 'cyberpunk'
              | 'handmade'
              | 'retroWave'
              | 'neonDrip'
              | 'slimer'
              | 'arcade'
              | 'tropicalPunch'
              | 'discoFloor'
              | 'vinylGroove'
              | 'zigzag'
              | 'midCentury'
              | 'retroTriangle'
              | 'retroWave70s'
              | 'synthwave'
              | 'hypnotic'
              | 'pinwheel'
              | 'galaxy'
              | 'patchwork'
              | 'stitches'
              | 'puzzle'
              | 'instagram'
              | 'whatsapp'
              | 'youtube'
              | 'tiktok'
              | 'linkedin'
              | 'facebook'
              | 'darkBush'
              | 'minecraft'
              | 'architecture'
              | 'candyBlocks'
              | 'escher'
              | 'dither'
              | 'ditherRainbow'
              | 'deepBlue'
              | 'oldFilm'
              | 'el-nino'
              | 'petals'
              | 'washi-tape'
              | 'comic-fries'
              | 'vernissage'
              | 'comic-bricks'
              | 'windswept'
              | 'woodwork'
              | 'blotchy'
              | 'morseCode'
              | 'ripple'
              | 'florist'
              | 'boa'
            /** @enum {string} */
            moduleStyleId?:
              | 'classic'
              | 'photo-overlay'
              | 'bacteria'
              | 'blocky'
              | 'botanical'
              | 'bubbles'
              | 'calligraphy'
              | 'vortex'
              | 'chevron'
              | 'circuits'
              | 'connected'
              | 'diamond'
              | 'doodle'
              | 'double-bubble'
              | 'drip'
              | 'explosion'
              | 'film'
              | 'ink-pen'
              | 'washi-tape'
              | 'comic-fries'
              | 'woodwork'
              | 'blotchy'
              | 'glitch'
              | 'grass'
              | 'halfmoon'
              | 'leaves'
              | 'characters'
              | 'brixx'
              | 'wavy'
              | 'dither'
              | 'megaShapes'
              | 'mosaic'
              | 'neighborAware'
              | 'organic'
              | 'pacman'
              | 'patchwork'
              | 'pizza'
              | 'puzzle'
              | 'raindrop'
              | 'artist'
              | 'paint-strokes'
              | 'retro'
              | 'rotated'
              | 'roundedDots'
              | 'roundedSquares'
              | 'tetris'
              | 'sketch'
              | '3d'
              | 'triangle'
              | 'spiky'
              | 'overlay'
              | 'petals'
              | 'variedDots'
              | 'ripple'
              | 'isometric'
            moduleStyleParams?: {
              [key: string]: number | string
            }
            /** @enum {string} */
            finderStyleId?:
              | 'classic'
              | 'modern'
              | 'carved'
              | 'scribble'
              | 'drip'
              | 'eroded'
              | 'comic'
              | 'blotchy'
              | 'shifted'
              | 'meadow'
              | 'leaf'
              | 'morphing'
              | 'pill'
              | 'sketchy'
              | 'stamp'
              | 'sticker'
              | 'segmented'
              | 'dotted'
            finderStyleParams?: {
              [key: string]: number | string
            }
            finderUseModuleStyle?: boolean
            finderColorInherit?: boolean
            moduleColor?:
              | string
              | {
                  /** @enum {string} */
                  type: 'linear' | 'radial'
                  angle?: number
                  stops: (
                    | string
                    | {
                        color: string
                        offset: number
                      }
                  )[]
                }
            modulePalette?: string[]
            /** @enum {string} */
            paletteMode?:
              | 'scatter'
              | 'horizontal'
              | 'vertical'
              | 'diagonal'
              | 'radial'
              | 'checkerboard'
              | 'spiral'
              | 'wave'
              | 'noise'
              | 'rings'
              | 'mandala'
              | 'lava'
              | 'group'
            paletteScale?: number
            paletteDither?: number
            finderFrameColor?:
              | string
              | {
                  /** @enum {string} */
                  type: 'linear' | 'radial'
                  angle?: number
                  stops: (
                    | string
                    | {
                        color: string
                        offset: number
                      }
                  )[]
                }
            finderEyeColor?:
              | string
              | {
                  /** @enum {string} */
                  type: 'linear' | 'radial'
                  angle?: number
                  stops: (
                    | string
                    | {
                        color: string
                        offset: number
                      }
                  )[]
                }
            background?: string | 'transparent'
            margin?: number
            logo?:
              | {
                  /** @enum {string} */
                  id:
                    | 'youtube'
                    | 'instagram'
                    | 'facebook'
                    | 'x'
                    | 'linkedin'
                    | 'tiktok'
                    | 'snapchat'
                    | 'pinterest'
                    | 'threads'
                    | 'bluesky'
                    | 'whatsapp'
                    | 'telegram'
                    | 'discord'
                    | 'spotify'
                    | 'apple'
                    | 'twitch'
                    | 'website'
                    | 'email'
                    | 'phone'
                    | 'location'
                    | 'wifi'
                    | 'google'
                    | 'paypal'
                    | 'amazon'
                    | 'googleplay'
                    | 'github'
                    | 'kim'
                  color: string
                  regionWidth?: number
                  /** @enum {string} */
                  mode?: 'clear' | 'float' | 'fill'
                  halo?: number
                  fillInterior?: boolean
                  posX?: number
                  posY?: number
                }
              | {
                  data: string
                  regionWidth?: number
                  /** @enum {string} */
                  mode?: 'clear' | 'float' | 'fill'
                  halo?: number
                  fillInterior?: boolean
                  posX?: number
                  posY?: number
                }
            halo?: {
              enabled?: boolean
              /** @enum {string} */
              mode?: 'composite' | 'unified'
              quietZone?: number
              spread?: number
              margin?: number
              density?: number
              /** @enum {string} */
              curve?: 'none' | 'linear' | 'ease' | 'steep'
              /** @enum {string} */
              falloff?: 'square' | 'squircle' | 'round'
              cluster?: number
              seed?: number
              color?: {
                /** @enum {string} */
                mode?: 'inherit' | 'palette'
                palette?: string[]
                /** @enum {string} */
                paletteMode?:
                  | 'scatter'
                  | 'horizontal'
                  | 'vertical'
                  | 'diagonal'
                  | 'radial'
                  | 'checkerboard'
                  | 'spiral'
                  | 'wave'
                  | 'noise'
                  | 'rings'
                  | 'mandala'
                  | 'lava'
                  | 'group'
                fade?: number
              }
            }
          }
          /**
           * @default svg
           * @enum {string}
           */
          format?: 'svg' | 'png'
          size?: number
          /** @default true */
          fixContrast?: boolean
        }
      }
    }
    responses: {
      /** @description The rendered QR code image — SVG or PNG per the requested `format`. The response `Content-Type` names the format actually returned and is authoritative. */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'image/svg+xml': string
          'image/png': string
        }
      }
      /** @description Content or design failed validation, or the format is unsupported. */
      400: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description API key missing, malformed, unknown, or revoked. */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Custom logo or requested PNG size over the cap. */
      413: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Valid input that cannot be encoded — usually content too long for a QR code. */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Rate limit exceeded. Carries `retry-after` (seconds to wait) plus `x-ratelimit-limit`, `x-ratelimit-remaining` and `x-ratelimit-reset` (seconds until the window resets). Successful responses carry the three `x-ratelimit-*` headers too, so a client can pace itself without ever provoking a 429. */
      429: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
      /** @description Render failure. Logged on our side. */
      500: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': {
            error: {
              code: string
              message: string
            }
          }
        }
      }
    }
  }
}
